language: python
env:
  - text=asd
python:
  - "3.6"
install:
  - pip install .
script:
  - python setup.py bdist_wheel
  - echo $TRAVIS_PULL_REQUEST 
  - echo $text
before_deploy:
  - git config --local user.name $TRAVIS_PULL_REQUEST 
  - git config --local user.email $text
deploy:
  provider: releases
  user: $GITHUB_USERNAME
  password: $GITHUB_PASSWORD
  file: "dist/*.whl"
  skip_cleanup: true
#  on:
#    tags: true
