language: python
env:
  - text=asd
python:
  - "3.6"
install:
  - pip install .
script:
  - python setup.py bdist_wheel
deploy:
  provider: releases
  api_key: "3b81ec17888eae092a5827f24b74a9cf83e06400"
  user: "balashovartem"
  password: "a123456"
  file: "dist/*.whl"
  skip_cleanup: true
#  on:
#    tags: true
