language: python
python:
  - "3.6"
install:
  - pip install .
script:
  - python setup.py bdist_wheel
deploy:
  provider: releases
  api_key: "GITHUB_OAUTH_TOKEN"
  file: "dist/*.whl"
  skip_cleanup: true
#  on:
#    tags: true
