language: python
env:
  - text=asd
python:
  - "3.6"
install:
  - pip install .
script:
  - python setup.py bdist_wheel
before_deploy:
  - git config --local user.name "balashovartem"
  - git config --local user.email "balashov.artem@gmail.com"
  - git tag "$(date +'%Y%m%d%H%M%S')-$(git log --format=%h -1)"  
deploy:
  provider: releases
  prerelease: true
  api_key: "ef567c2132e4d38826225b3259a18f7d373f2d40"
  skip_cleanup: true
  file: 
    - dist/lamp-0.1-py2.py3-none-any.whl
  
#  on:
#    tags: true
